server:
  port: 8888

resilience4j:
  circuitbreaker:
    instances:
      tag-upload-file-cb:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 50
        failureRateThreshold: 80
        slowCallDurationThreshold: 5000ms
        slowCallRateThreshold: 80
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10

      tag-toggle-cb:
        registerHealthIndicator: true
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 70
        slowCallDurationThreshold: 3000ms
        slowCallRateThreshold: 70
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10

      tagUpdateCB:
        registerHealthIndicator: true
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 70
        slowCallDurationThreshold: 3000ms
        slowCallRateThreshold: 70
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 8

      tagToggleCB:
        registerHealthIndicator: true
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 70
        slowCallDurationThreshold: 3000ms
        slowCallRateThreshold: 70
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 8

      tagCreateCB:
        registerHealthIndicator: true
        slidingWindowSize: 50
        minimumNumberOfCalls: 20
        failureRateThreshold: 70
        slowCallDurationThreshold: 3000ms
        slowCallRateThreshold: 70
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 8

      tagGetCB:
        registerHealthIndicator: true
        slidingWindowSize: 200
        minimumNumberOfCalls: 50
        failureRateThreshold: 85
        slowCallDurationThreshold: 6000ms
        slowCallRateThreshold: 85
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 20

      tagDeleteCB:
        registerHealthIndicator: true
        slidingWindowSize: 40
        minimumNumberOfCalls: 15
        failureRateThreshold: 60
        slowCallDurationThreshold: 3000ms
        slowCallRateThreshold: 60
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5

  retry:
    instances:
      super-adm-retry:
        maxAttempts: 7
        waitDuration: 6s
        retryExceptions:
          - org.springframework.dao.DataAccessException

      create-retry:
        maxAttempts: 3
        waitDuration: 4s
        retryExceptions:
          - org.springframework.dao.DataAccessException

      delete-retry:
        maxAttempts: 3
        waitDuration: 4s
        retryExceptions:
          - org.springframework.dao.DataAccessException

      update-retry:
        maxAttempts: 2
        waitDuration: 5s
        retryExceptions:
          - org.springframework.dao.DataAccessException

s3:
  bucketAttachments: attachments

spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 30
          max-idle: 20
          min-idle: 4

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
        region: us-east-1
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      path-style: true

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4000/social_network_java_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  argon:
    saltLength: 16
    hashLength: 32
    parallelism: 1
    memory: 65536
    iterations: 3
  application:
    name: writeapi
  front:
    url: http://localhost:3000
  security:
    exp:
      token: 24
      refresh: 444444
    jwt:
      secret: 5438y43v734vb7t40yt7y7rft47r7tv43htf3ht40f7t430ft0ft3t4fh94t3r3653667586578784658467867846786667v
snowflake:
  worker-id: 5
  datacenter-id: 1