server:
  port: 8889 # Porta diferente para evitar conflitos se o app principal estiver rodando

resilience4j:
  circuitbreaker:
    enabled: false # Desativa todos os Circuit Breakers por padrão nos testes
  retry:
    enabled: false # Desativa os Retries para os testes serem determinísticos

spring:
  sql:
    init:
      mode: always

  application:
    name: writeapi-test

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  threads:
    virtual:
      enabled: true

  # LocalStack / S3 Mocks para testes
  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
      credentials:
        access-key: test
        secret-key: test

# Mantemos as configs de Argon2 iguais para garantir que o login funcione nos testes
argon:
  saltLength: 16
  hashLength: 32
  parallelism: 1
  memory: 4096 # Reduzido para os testes rodarem mais rápido (menos CPU)
  iterations: 1

# JWT fixo e curto para facilitar os testes de integração
security:
  exp:
    token: 1
    refresh: 2
  jwt:
    secret: test_secret_key_must_be_long_enough_to_avoid_validation_errors_123456789

snowflake:
  worker-id: 1
  datacenter-id: 1

s3:
  bucketAttachments: attachments